export const LAYER_ACTIONS = {
  SET_LAYERS: 'SET_LAYERS',

  ADD_LAYER: 'ADD_LAYER',

  REMOVE_LAYER: 'REMOVE_LAYER',

  TOGGLE_LAYER: 'TOGGLE_LAYER',

  SET_ACTIVE_LAYER: 'SET_ACTIVE_LAYER',

  SET_LAYER_OPACITY: 'SET_LAYER_OPACITY',

  SET_LOADING_LAYERS: 'SET_LOADING_LAYERS',

  SET_LAYER_ERROR: 'SET_LAYER_ERROR',

  TOGGLE_GROUP: 'TOGGLE_GROUP',

  TOGGLE_GROUP_EXPANDED: 'TOGGLE_GROUP_EXPANDED',

  MOVE_NODE: 'MOVE_NODE',

  UPDATE_LAYER: 'UPDATE_LAYER',

  REORDER_LAYER: 'REORDER_LAYER',

  ADD_LAYER_TO_GROUP:
    'ADD_LAYER_TO_GROUP',
  UPDATE_FEATURE_IN_LAYER:
    'UPDATE_FEATURE_IN_LAYER',
  MARK_LAYER_DIRTY:
  'MARK_LAYER_DIRTY',

CLEAR_LAYER_DIRTY:
  'CLEAR_LAYER_DIRTY',

SAVE_LAYER: 'SAVE_LAYER',

SAVE_ALL_LAYERS: 'SAVE_ALL_LAYERS',

SET_LAYER_SAVING: 'SET_LAYER_SAVING',

SET_LAYER_SYNC_ERROR:
  'SET_LAYER_SYNC_ERROR',



}