export const LAYER_ACTIONS = {
  SET_LAYERS: 'SET_LAYERS',

  ADD_LAYER: 'ADD_LAYER',

  REMOVE_LAYER: 'REMOVE_LAYER',

  TOGGLE_LAYER: 'TOGGLE_LAYER',

  SET_ACTIVE_LAYER: 'SET_ACTIVE_LAYER',

  SET_LAYER_OPACITY: 'SET_LAYER_OPACITY',

  SET_LOADING_LAYERS: 'SET_LOADING_LAYERS',

  SET_LAYER_ERROR: 'SET_LAYER_ERROR',

  UPDATE_OPACITY: 'UPDATE_OPACITY',

  MOVE_LAYER_UP: 'MOVE_LAYER_UP',

  MOVE_LAYER_DOWN: 'MOVE_LAYER_DOWN',

  TOGGLE_GROUP: 'TOGGLE_GROUP',
  
}