export const GIS_ACTIONS = {
  SET_LOADING: 'SET_LOADING',

  SET_ERROR: 'SET_ERROR',

  SET_SELECTED_FEATURE: 'SET_SELECTED_FEATURE',

  SET_SELECTED_FEATURES: 'SET_SELECTED_FEATURES',

  SET_MAP_CENTER: 'SET_MAP_CENTER',

  SET_ZOOM: 'SET_ZOOM',

  SET_ACTIVE_TOOL: 'SET_ACTIVE_TOOL',

  SET_FEATURE_INFO: 'SET_FEATURE_INFO',

  TOGGLE_DRAW_MODE: 'TOGGLE_DRAW_MODE',

  SET_VISIBLE_LAYERS: 'SET_VISIBLE_LAYERS',
}